# Generated by Django 4.2.2 on 2023-08-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=80, verbose_name='Pavadinimas')),
                ('metai', models.IntegerField(verbose_name='Pradejo-metai')),
                ('biografija', models.TextField(max_length=2000, verbose_name='Bio')),
            ],
        ),
    ]
