# Generated by Django 4.2.2 on 2023-08-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irasai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumas', models.CharField(max_length=100, verbose_name='Albumas')),
                ('metai_pasirode', models.IntegerField(verbose_name='Pirmo leidimo metai')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprasymas')),
                ('artistasFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irasas_set', to='irasai.artistas')),
            ],
        ),
    ]
