# Generated by Django 4.2.2 on 2023-08-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irasai', '0002_irasas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='metai',
            field=models.IntegerField(verbose_name='Pradėjo-metai'),
        ),
        migrations.AlterField(
            model_name='irasas',
            name='aprasymas',
            field=models.TextField(max_length=2000, verbose_name='Aprašymas'),
        ),
        migrations.CreateModel(
            name='Katalogas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprašymas')),
                ('artistasFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='katalogas_set', to='irasai.artistas')),
            ],
        ),
    ]
