# Generated by Django 4.2.2 on 2023-08-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irasai', '0004_katalogas_irasasfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogas',
            name='irasasFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='katalog_set', to='irasai.irasas'),
        ),
    ]
